### ISSUE TITLE
Error on command

### ISSUE THREAD

**Issue by themethaithian** [Ehhthan/MMOBuffs-Wiki#4]
I got this when run command

[14:31:04] [Server thread/INFO]: _reveN issued server command: /mmobuffs
[14:31:04] [Server thread/ERROR]: [ACF] Exception in command: mmobuffs 
[14:31:04] [Server thread/ERROR]: [ACF] java.lang.NoSuchMethodError: 'void org.bukkit.command.CommandSender.sendMessage(net.kyori.adventure.text.Component)'
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.command.MMOBuffsCommand.onUnknownCommand(MMOBuffsCommand.java:231)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.executeCommand(BaseCommand.java:577)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.execute(BaseCommand.java:513)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RootCommand.execute(RootCommand.java:99)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:829)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1941)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1780)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1761)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.TickTask.run(SourceFile:18)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
 
[14:31:04] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)
 
[14:31:13] [Server thread/INFO]: _reveN issued server command: /mmobuffs list
[14:31:13] [Server thread/ERROR]: [ACF] Exception in command: mmobuffs list 
[14:31:13] [Server thread/ERROR]: [ACF] java.lang.NoSuchMethodError: 'void org.bukkit.command.CommandSender.sendMessage(net.kyori.adventure.text.Component)'
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.command.MMOBuffsCommand.onListCommand(MMOBuffsCommand.java:223)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.executeCommand(BaseCommand.java:577)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.execute(BaseCommand.java:513)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RootCommand.execute(RootCommand.java:99)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:829)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1941)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1780)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1761)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.TickTask.run(SourceFile:18)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
 
[14:31:13] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)
 
[14:31:16] [Server thread/INFO]: _reveN issued server command: /mmobuffs reload
[14:31:16] [Server thread/ERROR]: [ACF] Exception in command: mmobuffs reload 
[14:31:16] [Server thread/ERROR]: [ACF] java.lang.NoSuchMethodError: 'void org.bukkit.command.CommandSender.sendMessage(net.kyori.adventure.text.Component)'
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.command.MMOBuffsCommand.onReloadCommand(MMOBuffsCommand.java:52)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.executeCommand(BaseCommand.java:577)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BaseCommand.execute(BaseCommand.java:513)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.RootCommand.execute(RootCommand.java:99)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at com.ehhthan.mmobuffs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:829)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1941)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1780)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1761)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.TickTask.run(SourceFile:18)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
 
[14:31:16] [Server thread/ERROR]: [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Ehhthan** [comment]
Paper is required.
